### PR TITLE
map dynamic library globals to root set

### PR DESCRIPTION
**Pull request by djichthys**
Add global data sections from dynamically linked libraries to mark stack when executing Garbage-Collection

### CODE REVIEW

**Comment by ltratt** [comment]
@djichthys Can you provide a bit of context / motivation for the PR please? I see lots of code, but because I'm very stupid, I don't know *why* this is useful.

**Comment by djichthys** [comment]
> @djichthys Can you provide a bit of context / motivation for the PR please? I see lots of code, but because I'm very stupid, I don't know _why_ this is useful.

Sure @ltratt . 

Without `DYNAMIC_LOADING` being defined, *BDWGC* only *marks* global variables in the compiled **executable**.  Variables in the `.data` and `.bss` sections of dynamically linked libraries are ignored in this scenario. 
Any global variables in additional libraries that are dynamically linked along with the executable were being ignored during the mark phase. Consequently, memory pointed to by capabilities stored in *dynamic-library-globals* were being *GC*'d. 

The code path taken for marking when `DYNAMIC_LOADING`  is turned **ON** is different. It happens in every *GC* cycle as opposed to just once in `GC_init()`  when `DYNAMIC_LOADING`  is turned **OFF**.  

The existing code was stripping off the *capability-tag*-bit  when deriving the *start* and *end* of the **globals** in each dynamically linked library.  In summary the PR

1. utilises a previous macro for checking for a valid `SPANNING_CAPABILITY`. To make it more useful, I have moved it to a header so that it can be used in both functions whether `DYNAMIC_LOADING` is switched **ON** or **OFF**. 
2. Re-derives a valid capability to  set the  global `.data`  and `.bss` sections as global roots in  the  mark-stack
     * with a valid tag 
     * with the right bounds to scan through these variables.

**Comment by ltratt** [comment]
Thanks -- I think I get it!

Are we able to add a test for this?

**Comment by ltratt** [comment]
I *think* you only need to add a capability test that is checked with `DYNAMIC_LOADING=1` ?

**Comment by djichthys** [comment]
> I _think_ you only need to add a capability test that is checked with `DYNAMIC_LOADING=1` ?

Ok will do just the richards test.

**Comment by djichthys** [comment]
bors try

**Comment by djichthys** [comment]
Ready to review again @ltratt . With the additional test.

**Comment by ltratt** [comment]
Dumb question: that test(s) wouldn't have worked before this PR?

**Comment by djichthys** [comment]
> Dumb question: that test(s) wouldn't have worked before this PR?

That is right @ltratt . The extra test (Richards wrapped in a dynamic library) would have failed with previous tests

**Comment by djichthys** [comment]
Ready to merge @ltratt .

**Comment by djichthys** [comment]
bors try

**Pull request merged**
